language: java
jdk:
 - openjdk8
 - openjdk11
notifications:
  email:
    recipients:
      - ismith14@students.towson.edu
    on_success: always # default: change
    on_failure: always # default: always
